DROP TABLE IF EXISTS player_match_stats;

CREATE TABLE player_match_stats AS
WITH base AS (
    SELECT
        concat(tourney_id, '|', match_num, '|', winner_id, '|', loser_id) AS match_id,
        source_file,
        level_group,
        tourney_id,
        tourney_name,
        surface,
        tourney_level,
        tourney_date,
        best_of,
        round,
        minutes,

        winner_id,
        winner_name,
        winner_hand,
        winner_ht,
        winner_ioc,
        winner_age,
        winner_rank,
        winner_rank_points,

        loser_id,
        loser_name,
        loser_hand,
        loser_ht,
        loser_ioc,
        loser_age,
        loser_rank,
        loser_rank_points,

        score,

        w_ace, w_df, w_svpt, w_1stin, w_1stwon, w_2ndwon, w_svgms, w_bpsaved, w_bpfaced,
        l_ace, l_df, l_svpt, l_1stin, l_1stwon, l_2ndwon, l_svgms, l_bpsaved, l_bpfaced
    FROM matches
)
SELECT
    match_id,
    source_file,
    level_group,
    tourney_id,
    tourney_name,
    surface,
    tourney_level,
    tourney_date,
    best_of,
    round,
    minutes,
    winner_id AS player_id,
    winner_name AS player_name,
    loser_id AS opponent_id,
    loser_name AS opponent_name,
    1 AS is_win,
    winner_hand AS player_hand,
    winner_ht AS player_ht,
    winner_ioc AS player_ioc,
    winner_age AS player_age,
    winner_rank AS player_rank,
    winner_rank_points AS player_rank_points,
    loser_hand AS opponent_hand,
    loser_ht AS opponent_ht,
    loser_ioc AS opponent_ioc,
    loser_age AS opponent_age,
    loser_rank AS opponent_rank,
    loser_rank_points AS opponent_rank_points,
    score,
    w_ace AS ace,
    w_df AS df,
    w_svpt AS svpt,
    w_1stin AS first_in,
    w_1stwon AS first_won,
    w_2ndwon AS second_won,
    w_svgms AS service_games,
    w_bpsaved AS bp_saved,
    w_bpfaced AS bp_faced,
    l_ace AS opp_ace,
    l_df AS opp_df,
    l_svpt AS opp_svpt,
    l_1stin AS opp_first_in,
    l_1stwon AS opp_first_won,
    l_2ndwon AS opp_second_won,
    l_svgms AS opp_service_games,
    l_bpsaved AS opp_bp_saved,
    l_bpfaced AS opp_bp_faced
FROM base

UNION ALL

SELECT
    match_id,
    source_file,
    level_group,
    tourney_id,
    tourney_name,
    surface,
    tourney_level,
    tourney_date,
    best_of,
    round,
    minutes,
    loser_id AS player_id,
    loser_name AS player_name,
    winner_id AS opponent_id,
    winner_name AS opponent_name,
    0 AS is_win,
    loser_hand AS player_hand,
    loser_ht AS player_ht,
    loser_ioc AS player_ioc,
    loser_age AS player_age,
    loser_rank AS player_rank,
    loser_rank_points AS player_rank_points,
    winner_hand AS opponent_hand,
    winner_ht AS opponent_ht,
    winner_ioc AS opponent_ioc,
    winner_age AS opponent_age,
    winner_rank AS opponent_rank,
    winner_rank_points AS opponent_rank_points,
    score,
    l_ace AS ace,
    l_df AS df,
    l_svpt AS svpt,
    l_1stin AS first_in,
    l_1stwon AS first_won,
    l_2ndwon AS second_won,
    l_svgms AS service_games,
    l_bpsaved AS bp_saved,
    l_bpfaced AS bp_faced,
    w_ace AS opp_ace,
    w_df AS opp_df,
    w_svpt AS opp_svpt,
    w_1stin AS opp_first_in,
    w_1stwon AS opp_first_won,
    w_2ndwon AS opp_second_won,
    w_svgms AS opp_service_games,
    w_bpsaved AS opp_bp_saved,
    w_bpfaced AS opp_bp_faced
FROM base;

CREATE INDEX idx_pms_player_date ON player_match_stats(player_id, tourney_date DESC);
CREATE INDEX idx_pms_opp_date ON player_match_stats(opponent_id, tourney_date DESC);
CREATE INDEX idx_pms_surface_date ON player_match_stats(surface, tourney_date DESC);
CREATE INDEX idx_pms_match_id ON player_match_stats(match_id);
